[package]
name = "gen_d"
version = "0.1.0"
authors = ["BradLyman <lyman.brad3211@gmail.com>"]

[dependencies]

[dependencies.sdl2]
version = "0.31"
default-features = true

[dependencies.gl]
version = "0.6.0"

